### Get version
GET {{base-url}}/info/version

### Get last run
GET {{base-url}}/info/last-run

### Start import for sensors manually
POST {{base-url}}/sensor-import/run

### Start import for sensor data manually
POST {{base-url}}/sensor-data-import/run

#########################################################################
### Agranimo API
#########################################################################

### Login into the API
POST https://public-staging.agranimo.com/auth/login
Content-Type: application/json

{
  "username": "{{username}}",
  "password": "{{password}}"
}

### Fetch zone
GET https://public-staging.agranimo.com/zone
Authorization: Bearer {{access-token}}